app = "hoger"

[[services]]
  internal_port = 80
  protocol = "http"

  [services.ports]
    handlers = ["http"]
    port = 4200

[[regions]]
  name = "ewr"
  routes = ["cdn"]

[[regions]]
  name = "sfo"
  routes = ["cdn"]

[[deploy.targets]]
  name = "frontend"
  dockerImage = "faaant/hoger-client:latest"